/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author darshana
 */
public class appointmentPanel extends javax.swing.JPanel  {

    String timeSlot;
    /**
     * Creates new form appointmentPanel
     */
    public appointmentPanel(javax.swing.JPanel appointPanel) {
        initComponents();
        time1Button.setVisible(true);
        time2Button.setVisible(true);
        off_nameLabel.setVisible(false);
        offnameLabel.setVisible(false);
        time1Button.setActionCommand("09:00 am - 12:00 pm");
        time2Button.setActionCommand("01:00 pm - 04:00 pm");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        time = new javax.swing.ButtonGroup();
        successLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        id_textField = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();
        appointLabel = new javax.swing.JLabel();
        appointdateLabel = new javax.swing.JLabel();
        appointtimeslotLabel = new javax.swing.JLabel();
        appointidLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        time1Button = new javax.swing.JRadioButton();
        time2Button = new javax.swing.JRadioButton();
        saveButton = new javax.swing.JButton();
        offnameLabel = new javax.swing.JLabel();
        off_nameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        successLabel.setForeground(new java.awt.Color(0, 128, 0));
        successLabel.setText("You have successfully registered");

        idLabel.setText("Enter your applicant id:");

        viewButton.setText("View Details");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        appointtimeslotLabel.setText("Select a time slot:");

        time.add(time1Button);
        time1Button.setText("09:00am-12:00pm");

        time.add(time2Button);
        time2Button.setText("01:00pm-04:00pm");
        time2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time2ButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Exit");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        offnameLabel.setText("Officer Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(appointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(appointidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabel)
                                    .addComponent(appointtimeslotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(time2Button)
                                    .addComponent(time1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(offnameLabel)
                                    .addComponent(appointdateLabel))
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(off_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addGap(302, 302, 302))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(successLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(time1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time2Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(appointtimeslotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appointidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(appointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointdateLabel)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(off_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(offnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        if(evt.getSource() == viewButton){
            timeSlot = time.getSelection().getActionCommand();
            System.out.println(timeSlot);
            String id = id_textField.getText();
            String off_id = null;
            String off_name = null;
            int appointment_id = Integer.parseInt(id);
            Connection conn=null;
            
            java.sql.Date date = null;         
            
            appointLabel.setText("Appointment id:");
            appointidLabel.setText(id);
            String sql = "Select getDate()";
            String sql1 = "Select getOfficer();";

            Statement x,z = null;
            try {
                Class.forName("org.postgresql.Driver");
                conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","tina","batman123");
                x = conn.createStatement();
                z = conn.createStatement();
                ResultSet res = x.executeQuery(sql);
                while(res.next()){
                    date = res.getDate("getdate");
                }
                appointdateLabel.setText("Appointment date:");
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                String dateText = df.format(date);
                dateLabel.setText(dateText);
                System.out.println(date);

                ResultSet res2 = z.executeQuery(sql1);
                while(res2.next()){
                    off_id = res2.getString("getofficer");
                }

                String sql2 = "Insert into appointment values( "+appointment_id+",'"+date+"',"+appointment_id+",'"+off_id+"','"+timeSlot+"');";
                z.executeUpdate(sql2);
                String sql3 = "Select officer_name from officer where officer_id = '"+off_id+"'";
                ResultSet res3 = z.executeQuery(sql3);
                while(res3.next()){
                    off_name = res3.getString("officer_name");
                }
                System.out.println(off_name);
                
                offnameLabel.setVisible(true);
                off_nameLabel.setVisible(true);
                off_nameLabel.setText(off_name);

            }       

            catch (ClassNotFoundException ex) {
               Logger.getLogger(appointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(appointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
           } 
            finally {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(appointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
   
            
        }   
    }//GEN-LAST:event_viewButtonActionPerformed

    private void time2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time2ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time2ButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointLabel;
    private javax.swing.JLabel appointdateLabel;
    private javax.swing.JLabel appointidLabel;
    private javax.swing.JLabel appointtimeslotLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField id_textField;
    private javax.swing.JLabel off_nameLabel;
    private javax.swing.JLabel offnameLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel successLabel;
    private javax.swing.ButtonGroup time;
    private javax.swing.JRadioButton time1Button;
    private javax.swing.JRadioButton time2Button;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables

   

}
