/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author darshana
 */
public class loginPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form loginPanel
     */
    public loginPanel() {
        initComponents();            
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userType = new javax.swing.JComboBox();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        user_textField = new javax.swing.JTextField();
        pass_textField = new javax.swing.JPasswordField();
        goButton = new javax.swing.JButton();
        emblemLabel = new javax.swing.JLabel();
        courtesyLabel = new javax.swing.JLabel();
        officialCheck = new javax.swing.JRadioButton();
        applicantCheck = new javax.swing.JRadioButton();
        registerButton = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        userType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 255, 255));

        userLabel.setText("Username:");

        passLabel.setForeground(new java.awt.Color(0, 0, 0));
        passLabel.setText("Password:");

        user_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_textFieldActionPerformed(evt);
            }
        });

        goButton.setText("Login");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        courtesyLabel.setText("Created by: Anjana S, Tina Johnson, Darshana Padmadas");

        officialCheck.setText("Official");

        applicantCheck.setText("Applicant");

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        headingLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        headingLabel.setText("PASSPORT SEVA KENDRA");

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/tina/NetBeansProjects/JavaApplication1/src/javaapplication1/india.gif")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(emblemLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(user_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pass_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(registerButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(officialCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(applicantCheck)))
                        .addGap(137, 137, 137))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(courtesyLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userLabel)
                            .addComponent(user_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(officialCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applicantCheck)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(goButton)
                            .addComponent(registerButton))
                        .addGap(167, 167, 167)
                        .addComponent(courtesyLabel)
                        .addGap(452, 452, 452))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emblemLabel)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        try {
            int username =  Integer.parseInt(user_textField.getText());
            String offUser = user_textField.getText();
            String password = new String(pass_textField.getPassword());
            
            //System.out.println(password);
            //System.out.println(offUser);
            Connection conn = null;
            Statement x,y;
            Class.forName("org.postgresql.Driver");
            conn=DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","tina","batman123");
            
            if(evt.getSource() == goButton && officialCheck.isSelected() && !applicantCheck.isSelected()){
                officerPanel o1 = new officerPanel(this,offUser);
                String sql4 = "Select officer_id,password from officer where EXISTS(Select officer_id,password from officer where officer_id = '"+offUser+ "' and password = '"+password+"' ) and officer_id = '"+offUser+"'";
                y = conn.createStatement();
                ResultSet res1 = y.executeQuery(sql4);
                //System.out.println(sql4);
                
                if(res1.next() == false)
                    JOptionPane.showMessageDialog(null,"Invalid username or password");
                else{
                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    this.add(o1);
                    this.repaint();
                    this.revalidate();
                }
            }
            if(evt.getSource() == goButton && applicantCheck.isSelected() && !officialCheck.isSelected() ){
                
                
                String sql = "Select applicant_id,password from applicant where EXISTS(Select applicant_id,password from applicant where applicant_id ="+username+ " and password = '"+password+"' ) and applicant_id ="+username;
                int userArg = 0;
                x = conn.createStatement();
                ResultSet res = x.executeQuery(sql);
                System.out.println(sql);
                
                if(res.next() == false)
                    JOptionPane.showMessageDialog(null,"Invalid username or password");
                else{
                    
                    applicantViewPanel av1 = new applicantViewPanel(this, username);
                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    this.add(av1);
                    this.repaint();
                    this.revalidate();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(loginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(loginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if(evt.getSource() == registerButton && applicantCheck.isSelected() && !officialCheck.isSelected()){
            registerPanel r1 = new registerPanel(this);
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(r1);
            this.repaint();
            this.revalidate();
            Statement s;
            Connection conn=null;
            try {
            Class.forName("org.postgresql.Driver");
            conn=DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","tina","batman123");
             s = conn.createStatement();
            
            
            
        } catch ( SQLException e ) {
            e.printStackTrace();
            System.err.println( e.getClass().getName()+ " "+e.getMessage());
        }   catch (ClassNotFoundException ex) { 
                Logger.getLogger(loginPanel.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void user_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_textFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton applicantCheck;
    private javax.swing.JLabel courtesyLabel;
    private javax.swing.JLabel emblemLabel;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton officialCheck;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField pass_textField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JComboBox userType;
    private javax.swing.JTextField user_textField;
    // End of variables declaration//GEN-END:variables


}
