/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.ScrollPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darshana
 */
public class officerPanel extends javax.swing.JPanel {
    
    String offId;int app_id;
    String value;
    /**
     * Creates new form officerPanel
     */
    public officerPanel(javax.swing.JPanel o1, String id) {
        try {
            initComponents();
            o1.removeAll();
            Statement stmt;
            Connection conn;
            offId = id;String offName = null;
            resProofLabel.setVisible(false);
            edQualLabel.setVisible(false);
            identPoofLabel.setVisible(false);
            verify1Button.setVisible(false);
            verify2Button.setVisible(false);
            verifyLabel.setVisible(false);
            verify1Button.setSelected(false);
            verify2Button.setSelected(true);
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","tina","batman123");
            stmt = conn.createStatement();
            String sql1 = "Select officer_name from officer where officer_id = '"+offId+"'";
            ResultSet res1 = stmt.executeQuery(sql1);
            
            while(res1.next()){
                offName = res1.getString("Officer_name");
            }
            offIdLabel.setText(offId);
            offNameLabel.setText(offName);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(officerPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(officerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verifyButtonGroup = new javax.swing.ButtonGroup();
        officerinfoLabel = new javax.swing.JLabel();
        officeridLabel = new javax.swing.JLabel();
        officernameLabel = new javax.swing.JLabel();
        offappLabel = new javax.swing.JLabel();
        viewButton = new javax.swing.JButton();
        appIdField = new javax.swing.JTextField();
        resProofLabel = new javax.swing.JLabel();
        resLabel = new javax.swing.JLabel();
        edQualLabel = new javax.swing.JLabel();
        edLabel = new javax.swing.JLabel();
        identPoofLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        offIdLabel = new javax.swing.JLabel();
        offNameLabel = new javax.swing.JLabel();
        verifyLabel = new javax.swing.JLabel();
        verify2Button = new javax.swing.JRadioButton();
        doneButton = new javax.swing.JButton();
        verify1Button = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        officerinfoLabel.setForeground(new java.awt.Color(0, 128, 0));
        officerinfoLabel.setText("Officer Information");

        officeridLabel.setText("Officer ID:");

        officernameLabel.setText("Officer Name:");

        offappLabel.setText("Enter the Applicant ID:");

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        resProofLabel.setText("Residential Proof:");

        edQualLabel.setText("Educational Qualification:");

        identPoofLabel.setText("Identity Proof:");

        verifyLabel.setText("Transcripts Verified:");

        verifyButtonGroup.add(verify2Button);
        verify2Button.setText("No");
        verify2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify2ButtonActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        verifyButtonGroup.add(verify1Button);
        verify1Button.setText("Yes");
        verify1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(offappLabel)
                            .addComponent(resProofLabel)
                            .addComponent(edQualLabel)
                            .addComponent(identPoofLabel)
                            .addComponent(officeridLabel)
                            .addComponent(officernameLabel)
                            .addComponent(verifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(appIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                        .addComponent(edLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(offIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(offNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verify2Button)
                                    .addComponent(verify1Button)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(viewButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(doneButton)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(officerinfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(officerinfoLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officeridLabel)
                    .addComponent(offIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(officernameLabel)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(offappLabel)
                            .addComponent(appIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(viewButton)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resProofLabel)))
                    .addComponent(offNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edQualLabel)
                    .addComponent(edLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identPoofLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(verifyLabel)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verify1Button)
                        .addGap(18, 18, 18)))
                .addComponent(verify2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(doneButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    
  
    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        if( evt.getSource() == viewButton){
            try {
            
            Connection conn;
            Statement stmt;
            String rProof = null,IdProof = null,edQual = null;
            app_id = Integer.parseInt(appIdField.getText());
            verify1Button.setActionCommand("Yes");
            verify2Button.setActionCommand("No");
            
            
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","tina","batman123");
            stmt = conn.createStatement();
            
            String sql = "Select * from transcripts where trans_id = (Select trans_id from applicant where applicant_id = " +app_id+")";
            ResultSet res = stmt.executeQuery(sql);
            
            while(res.next()){
                
                edQual = res.getString("ed_qualification");
                IdProof = res.getString("identity_proof");
                rProof = res.getString("residential_proof");
            }
            
            
            resProofLabel.setVisible(true);
            edQualLabel.setVisible(true);
            identPoofLabel.setVisible(true);
            resLabel.setText(rProof);
            edLabel.setText(edQual);
            idLabel.setText(IdProof);
            verify1Button.setVisible(true);
            verify2Button.setVisible(true);
            verifyLabel.setVisible(true);
           // System.out.println(verifyButtonGroup.getSelection().getActionCommand());
               
            

            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(officerPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(officerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        if(evt.getSource() == doneButton){
            try {
                    Statement stmt;
                    Connection conn;
                    Class.forName("org.postgresql.Driver");
                    conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","tina","batman123");
                    stmt = conn.createStatement();
                    if(value == "Yes"){
                        String sql1 = "Insert into verify values('"+offId+"',"+app_id+",'Yes')";
                        stmt.executeUpdate(sql1);
                    }
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(officerPanel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(officerPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            System.exit(0);
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void verify1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify1ButtonActionPerformed
            if(verifyButtonGroup.getSelection().getActionCommand() == "Yes"){
                value = "Yes";
            }
    }//GEN-LAST:event_verify1ButtonActionPerformed

    private void verify2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify2ButtonActionPerformed
        if(verifyButtonGroup.getSelection().getActionCommand() == "No"){
                value = "No";
            }
    }//GEN-LAST:event_verify2ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appIdField;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel edLabel;
    private javax.swing.JLabel edQualLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel identPoofLabel;
    private javax.swing.JLabel offIdLabel;
    private javax.swing.JLabel offNameLabel;
    private javax.swing.JLabel offappLabel;
    private javax.swing.JLabel officeridLabel;
    private javax.swing.JLabel officerinfoLabel;
    private javax.swing.JLabel officernameLabel;
    private javax.swing.JLabel resLabel;
    private javax.swing.JLabel resProofLabel;
    private javax.swing.JRadioButton verify1Button;
    private javax.swing.JRadioButton verify2Button;
    private javax.swing.ButtonGroup verifyButtonGroup;
    private javax.swing.JLabel verifyLabel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
