/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author darshana
 */
public class registerPanel extends javax.swing.JPanel {
 
    /**
     * Creates new form registerPanel
     */
    public registerPanel(javax.swing.JPanel oldPanel) {
        oldPanel.removeAll();
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identityProof = new javax.swing.ButtonGroup();
        residentialProof = new javax.swing.ButtonGroup();
        nameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        name_textField = new javax.swing.JTextField();
        dob_textField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        email_textField = new javax.swing.JTextField();
        educationLabel = new javax.swing.JLabel();
        address_textField = new javax.swing.JTextField();
        tenthCheck = new javax.swing.JCheckBox();
        twelvthCheck = new javax.swing.JCheckBox();
        undergradCheck = new javax.swing.JCheckBox();
        gradCheck = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        cityLabel = new javax.swing.JLabel();
        city_textField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        country_textField = new javax.swing.JTextField();
        state_textField = new javax.swing.JTextField();
        rationCheck = new javax.swing.JRadioButton();
        aadharCheck = new javax.swing.JRadioButton();
        birthcerCheck = new javax.swing.JRadioButton();
        identityLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phone_textField = new javax.swing.JTextField();
        residentialLabel = new javax.swing.JLabel();
        residentialYesCheck = new javax.swing.JCheckBox();
        residentialNoCheck = new javax.swing.JCheckBox();
        backButton = new javax.swing.JButton();
        passLabel = new javax.swing.JLabel();
        password_Field = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setText("Name:");

        dobLabel.setText("Date of Birth:");

        addressLabel.setText("Address:");

        emailLabel.setText("email id:");

        educationLabel.setText("Educational Qualifications:");

        tenthCheck.setText("10th Class");

        twelvthCheck.setText("12th Class");

        undergradCheck.setText("Undergraduate/Diploma");

        gradCheck.setText("Graduate and Above");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cityLabel.setText("City");

        city_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_textFieldActionPerformed(evt);
            }
        });

        stateLabel.setText("State:");

        countryLabel.setText("Country:");

        identityProof.add(rationCheck);
        rationCheck.setText("Ration Card");

        identityProof.add(aadharCheck);
        aadharCheck.setText("Aadhar Card");
        aadharCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharCheckActionPerformed(evt);
            }
        });

        identityProof.add(birthcerCheck);
        birthcerCheck.setText("Birth Certificate");
        birthcerCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthcerCheckActionPerformed(evt);
            }
        });

        identityLabel.setText("Identity Proof:");

        phoneLabel.setText("Phone:");

        residentialLabel.setText("Residential Proof");

        residentialProof.add(residentialYesCheck);
        residentialYesCheck.setText("Tax Bill");
        residentialYesCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentialYesCheckActionPerformed(evt);
            }
        });

        residentialProof.add(residentialNoCheck);
        residentialNoCheck.setText("Other Records");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        passLabel.setText("Set your password");

        password_Field.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(emailLabel)
                            .addComponent(identityLabel)
                            .addComponent(residentialLabel)
                            .addComponent(phoneLabel)
                            .addComponent(countryLabel)
                            .addComponent(cityLabel)
                            .addComponent(passLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(city_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                        .addComponent(country_textField))
                                                    .addGap(66, 66, 66)
                                                    .addComponent(stateLabel))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rationCheck)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(gradCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(undergradCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(twelvthCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(tenthCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(aadharCheck)
                                                    .addComponent(birthcerCheck)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(state_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(address_textField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                        .addComponent(name_textField)
                                        .addComponent(dob_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(residentialYesCheck)
                                            .addGap(28, 28, 28)
                                            .addComponent(residentialNoCheck)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(submitButton))
                            .addComponent(password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(educationLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dob_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phone_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(address_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(city_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(state_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLabel)
                    .addComponent(country_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(educationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tenthCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twelvthCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undergradCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradCheck)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(identityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(residentialLabel)
                            .addComponent(residentialYesCheck)
                            .addComponent(residentialNoCheck))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(rationCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aadharCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(birthcerCheck)
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(email_textField)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(evt.getSource() == submitButton) {
            try {
                this.getData();                
            } catch (ParseException ex) {
                Logger.getLogger(registerPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            appointmentPanel  ap1 = new appointmentPanel(this);
            this.removeAll();
            this.setLayout(new BorderLayout());
            this.add(ap1);
            this.repaint();
            this.revalidate();        
            
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void city_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_textFieldActionPerformed

    private void aadharCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadharCheckActionPerformed

    private void birthcerCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthcerCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthcerCheckActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       if(evt.getSource() == backButton) {
        this.removeAll();
        loginPanel old = new loginPanel();
        this.setLayout(new BorderLayout());
        this.add(old);
        this.repaint();
        this.revalidate();
       }
    }//GEN-LAST:event_backButtonActionPerformed

    private void residentialYesCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentialYesCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residentialYesCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aadharCheck;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField address_textField;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton birthcerCheck;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField city_textField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField country_textField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dob_textField;
    private javax.swing.JLabel educationLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField email_textField;
    private javax.swing.JCheckBox gradCheck;
    private javax.swing.JLabel identityLabel;
    private javax.swing.ButtonGroup identityProof;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField name_textField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField password_Field;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phone_textField;
    private javax.swing.JRadioButton rationCheck;
    private javax.swing.JLabel residentialLabel;
    private javax.swing.JCheckBox residentialNoCheck;
    private javax.swing.ButtonGroup residentialProof;
    private javax.swing.JCheckBox residentialYesCheck;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField state_textField;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox tenthCheck;
    private javax.swing.JCheckBox twelvthCheck;
    private javax.swing.JCheckBox undergradCheck;
    // End of variables declaration//GEN-END:variables
    
    private void getData() throws ParseException{
     /**
     * Retrieving data from textfields
     */ 
        
        String name = name_textField.getText();
        String dob = dob_textField.getText();
        String address = address_textField.getText();
        String city = city_textField.getText();
        String state = state_textField.getText();
        String education;
        if(tenthCheck.isSelected())
            education = "Tenth Grade";
        else if(twelvthCheck.isSelected())
            education = "Twelvth Grade"; 
        else if(undergradCheck.isSelected())
            education = "Undergraduate";
        else 
            education = "Graduate and above";
        String country = country_textField.getText();
        SimpleDateFormat format = new SimpleDateFormat("dd/mm/yyyy");
        java.util.Date parsed = format.parse(dob);
        java.sql.Date dateBirth = new java.sql.Date(parsed.getTime());
        String email = email_textField.getText();
        int phone = Integer.parseInt(phone_textField.getText());
        rationCheck.setActionCommand("Ration Card");
        aadharCheck.setActionCommand("Aadhar Card");
        birthcerCheck.setActionCommand("Birth Certificate");
        residentialYesCheck.setActionCommand("Tax Bill");
        residentialNoCheck.setActionCommand("Other records");
        String psswd  = new String(password_Field.getPassword());
        
        String identity = identityProof.getSelection().getActionCommand();
        String residential = residentialProof.getSelection().getActionCommand();
        System.out.println(identity);
        System.out.println(residential);
        /**
        * Initializing database
        */
        Statement x,y,z;
        Connection conn=null;
        String result1 = null, result2 = null, result3 = null;
        try {
            Class.forName("org.postgresql.Driver");
            conn=DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","tina","batman123");
            System.out.println("Connected to database");
            x = conn.createStatement();
            String sql = "Insert into address values (DEFAULT, '"+ address+"','"+city+"','"+state+"','"+country+"');";
            x.executeUpdate(sql);
            String sql1 = "Select currval('add_id');";
            ResultSet rs1 = x.executeQuery(sql1);
            while(rs1.next()){
                result1 = rs1.getString("currval");
                System.out.println(result1);
            }
            y = conn.createStatement();
            String sql2 = "Insert into transcripts values(DEFAULT, '"+identity+"','"+education+"','"+residential+"');";
            y.executeUpdate(sql2);
            String sql3 = "Select currval('transc_id');";
            ResultSet rs2 = y.executeQuery(sql3);
            System.out.println(sql);
            System.out.println(sql1);
            while(rs2.next()){
                result2 = rs2.getString("currval");
                System.out.println(result2);
            }
            String sql4 = "Insert into applicant values(DEFAULT,'"+name+"',"+phone+",'"+email+"','"+dob+"','"+result1+"','"+result2+"','"+psswd+"');";
            y.executeUpdate(sql4);
            String sql5 = "Select currval('appli_id');";
            ResultSet rs3 = y.executeQuery(sql5);
            while(rs3.next()){
                result3 = rs3.getString("currval");
                System.out.println(result3);
            }
            JOptionPane.showMessageDialog(null,"Your applicant id is "+result3+"!");
                      
            
        } catch (SQLException e ) {
            e.printStackTrace();
            System.err.println( e.getClass().getName()+ " "+e.getMessage());
        }   catch (ClassNotFoundException ex) { 
                Logger.getLogger(loginPanel.class.getName()).log(Level.SEVERE, null, ex);
            } 
        
        /**
        * Inserting data into tables
        */
        
        
    }
}
